### PR TITLE
fix/npe_on_accessing_getNativeAd

### LINKED ISSUE #166: Exception com.applovin.mediation.nativeAds.MaxNativeAd
### MAX Plugin Version

3.4.1, 3.5.0

### Flutter Version

3.16.3

### Device/Platform Info

Galaxy Tab A 7.0, Galaxy J2, Oppo A37f, Oppo A37, Oppo CPH1605, Vivo Y21L, Vivo V3, Vivo Y51A, Alps, Lenovo Mobile, Sprd, Huawei, Sharp

### Current Behavior

When I use the plugin, Firebase crash reports the following:

StandardMethodCodec.decodeEnvelope
io.flutter.plugins.firebase.crashlytics.FlutterError - PlatformException(error, Attempt to invoke interface method 'com.applovin.mediation.nativeAds.MaxNativeAd com.applovin.mediation.MaxAd.getNativeAd()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method'
package:flutter/src/services/message_codecs.dart:652

### Expected Behavior

_No response_

### How to Reproduce

I'm not sure how to proceed; my code aligns with the instructions. Has anyone else encountered a similar issue?

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by alhiwatan**
Fix #166 - NPE when accessing `com.applovin.mediation.MaxAd.getNativeAd()`.    The native adView must have been destroyed as soon as a native ad is loaded but before it is applied to all the asset views.

```
io.flutter.plugins.firebase.crashlytics.FlutterError - PlatformException(error, Attempt to invoke interface method 'com.applovin.mediation.nativeAds.MaxNativeAd com.applovin.mediation.MaxAd.getNativeAd()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method'
package:flutter/src/services/message_codecs.dart:652
```

### CODE REVIEW

File: applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAXNativeAdView.java [hunk 1]
```diff
@@ -304,6 +304,8 @@ public void onAdRevenuePaid(final MaxAd ad)
 
     private void addTitleView(final MethodCall call)
     {
+        if ( nativeAd == null ) return;
```
[the remark this answers is not in the document]
Comment (santoshbagadi) [reply applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAXNativeAdView.java:307]: Same for other calls below.

[the remark this answers is not in the document]
Comment (alhiwatan) [reply applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAXNativeAdView.java]: @santoshbagadi, `nativeAd` is now a parameter, please review.

File: applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAXNativeAdView.java [hunk 2]
```diff
@@ -103,42 +103,42 @@ public AppLovinMAXNativeAdView(final int viewId,
 
             if ( "addTitleView".equals( call.method ) )
             {
-                addTitleView( call );
+                if ( nativeAd != null ) addTitleView( call, nativeAd );
```
Comment (santoshbagadi) [inline applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAXNativeAdView.java:106]: I think we'd still have the same problem as before. We should skip the null check here, and pass it into the method and do the `null` check there instead. 

Same for other methods below.

Comment (thomasmso) [reply applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAXNativeAdView.java:106]: @alhiwatan - The issue is this code is not thread safe and `nativeAd` needs to be used in an atomic manner.

By extracting it into a local variable and having your code reference that local varaible, you prevent a potential race condition such that if `if ( nativeAd != null )` is `true`, but right after `nativeAd` is set to `null`. That's the issue of referencing the class field instead of a local var.

Comment (alhiwatan) [reply applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAXNativeAdView.java:106]: @thomasmso, thanks, please review the update.

**Review by thomasmso — APPROVED** [review]
Just saw your changes

**Review by santoshbagadi — APPROVED** [review]
